// Generated by CoffeeScript 1.3.1
(function() {
  var xhrContainer;

  window.privatizer = {};

  window.privatizer.xhrContainer = {
    count: 0,
    callbacks: []
  };

  xhrContainer = window.privatizer.xhrContainer;

  window.privatizer.request = function(data) {
    var request, responseObject, sendData;
    request = new XMLHttpRequest();
    responseObject = {
      requestID: data.requestID
    };
    request.addEventListener("load", function(response) {
      responseObject['text'] = response.target.responseText;
      responseObject['status'] = response.target.status;
      xhrContainer.callbacks[responseObject.requestID](responseObject);
      return responseObject;
    }, false);
    switch (data.type) {
      case "POST":
        request.open("POST", data.url, true);
        break;
      default:
        request.open("GET", data.url, true);
    }
    request.setRequestHeader("Content-Type", "application/x-www-form-urlencoded; charset=UTF-8");
    request.withCredentials = true;
    if (data.header) {
      request.setRequestHeader(data.header[0], data.header[1]);
    }
    if (data.content) {
      sendData = data.content;
    } else {
      sendData = null;
    }
    return request.send(sendData);
  };

}).call(this);
