"""enhanced user object

Revision ID: 1434d42a779b
Revises: None
Create Date: 2012-04-21 02:59:37.589577

"""

# revision identifiers, used by Alembic.
revision = '1434d42a779b'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('key', u'ownerid')
    op.drop_column('key', 'id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('key', sa.Column(u'id', sa.INTEGER(), nullable=False))
    op.add_column('key', sa.Column(u'ownerid', sa.INTEGER(), nullable=False))
    op.drop_column('key', 'resource_id')
    op.drop_column('key', 'owner_group_name')
    op.drop_column('key', 'owner_user_name')
    ### end Alembic commands ###
